#!/bin/sh
if [ "$UID" != "0" ]; then
	echo "OvzCP must be run as root"
	exit 1
fi
uname -r | grep openvz > /dev/null
if [ "$?" != 0 ]; then
	echo "OpenVZ kernel not detected. Check uname -r"
	exit 1
fi
cd `dirname $0`
for i in 21215 21216 21217 21218; do
	/opt/ovzcp/main.py --port=$i >> /var/log/ovzcp.log 2>&1 &
done
rm ovzpipe 2>/dev/null || true
touch ovzpipe
chmod 600 ovzpipe
./ovzpipe.py < ovzpipe >> /var/log/ovzcp.log 2>&1 &
